services:
  postgres:
    image: postgres:17-alpine
    stdin_open: true
    tty: true
    restart: always
    ports:
      - '5432:5432'
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./backend/migrations/init:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD:
      PGGSSENCMODE:
      POSTGRES_USER: "postgres"

volumes:
  db_data:
